<?php

namespace AppBundle\Repository;

/**
 * toutesAnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class toutesAnnoncesRepository extends \Doctrine\ORM\EntityRepository
{
}
